-- A lexical scanner generated by aflex
with text_io; use text_io;
with lexic_dfa; use lexic_dfa; 
with lexic_io; use lexic_io; 
--# line 1 "lexic.l"
-- Tots els caracters representables
-- Tots els caracters representables excepte la doble cometa
-- Totes les lletres que generaran les paraules clau
--# line 38 "lexic.l"


with lexic_io; use lexic_io; 
with lexic_dfa; use lexic_dfa;
with d_token; use d_token;
package a_lexic is 
	function yylex return token;
end a_lexic;
