with Decls.D_Arbre;
use decls.d_arbre;

package semantica.C_Arbre is

   procedure Rs_Inicialitzar_Analisis (Nombref: in String);
   procedure Rs_Finalitzar_Analisis;
   procedure Rs_Aturar_Analisis;
   procedure Rl_Identificador (pident: out Pnode; Nom: in String;
                               L,C: in Natural);
   procedure Rl_Literal_String (Pstring: out Pnode; Nom: in String;
                                L,C: in Natural);
   procedure Rl_Literal_caracter (Pcar: out Pnode; Nom: in String;
                                  L,C: in Natural);
   procedure Rl_Literal_Enter (Pent: out Pnode; Nom: in String; L,C: in Natural);
   procedure Rl_atom (Pent: out Pnode; L,C: in Natural);
   procedure Rs_Programa (Pprog: out Pnode; Pdecl_Proc: in Pnode);
   procedure Rs_Decl_Proc (Pdecl_Proc: out Pnode;
                           Pencap, Pdecls, Psents, Pidfinal: in Pnode);
   procedure Rs_Encap (Pencap: out Pnode; Pid_Proc, Pcenc: in Pnode);
   procedure rs_params (Pcenc: out Pnode; Pl_Param: in Pnode);
   procedure rs_params (Pcenc: out Pnode);
   procedure Rs_L_Param (Pl_Param: out Pnode; Pl_Param2, Pparam: in Pnode);
   procedure Rs_L_Param (Pl_Param: out Pnode; Pparam: in Pnode);
   procedure Rs_Param (Pparam: out Pnode;
                       Pidparam, Ptipusparam, Pidtipusparam: in Pnode);
   procedure rs_mode_in (Ptipus_Param: out Pnode);
   procedure rs_mode_out (Ptipus_Param: out Pnode);
   procedure rs_declaracions (Pdecls: out Pnode; Pcontlista, Pdecl: in Pnode);
   procedure rs_declaracions (Pdecls: out Pnode);
   procedure rs_declaracio_const (Pdecl: out Pnode; Pdecl_Const: in Pnode);
   procedure rs_declaracio_var (Pdecl: out Pnode; Pdecl_Var: in Pnode);
   procedure rs_declaracio_tipus (Pdecl: out Pnode; pdecl_tipus: in pnode);
   procedure rs_declaracio_proc (Pdecl: out Pnode; pdecl_proc: in pnode);
   procedure Rs_Decl_Const (Pdecl_Const: out Pnode;
                            Plistaid, Pidtipus, Pvalor: in Pnode);
   procedure rs_valor_literal (Pvalor: out Pnode; Plit: in Pnode);
   procedure rs_valor_s_menys (Pvalor: out Pnode; Plit_Neg: in Pnode);
   procedure rs_valor_id (Pvalor: out Pnode; Pid: in Pnode);
   procedure rs_valor_s_menys_id (Pvalor: out Pnode; Pid_neg: in Pnode);
   procedure Rs_Decl_Var (Pdecl_Var: out Pnode; Plistaid, Pidtipus: in Pnode);
   procedure rs_l_id (Plista_Id: out Pnode; Pcontlista, Pid: in Pnode);
   procedure rs_l_id (Plista_Id: out Pnode; Pid: in Pnode);
   procedure rs_decl_tipus_subrang (Pdecl_tipus: out Pnode; Pdecl_subr: in Pnode);
   procedure rs_decl_tipus_array (Pdecl_Tipus: out Pnode; Pdecl_Array: in Pnode);
   procedure rs_decl_tipus_record (Pdecl_tipus: out Pnode; Pdecl_record: in Pnode);
   procedure rs_decl_subrang (Pdecl_Subr: out Pnode;
                              Pid, Pidtipus, Pvlmin, Pvlmax: in Pnode);
   procedure rs_decl_array (Pdecl_Array: out Pnode;
                            Pid, Plistaid, Pidtipus: in Pnode);
   procedure Rs_Decl_Record (Pdecl_Record: out Pnode; Pid, Pdecl_Camps: in Pnode);
   procedure Rs_Decl_Camps (Pdecl_Camps: out Pnode;
                            Pcontlista, Pdecl_Camp: in Pnode);
   procedure Rs_Decl_camps (Pdecl_camps: out Pnode);
   procedure Rs_Decl_Camp (Pdecl_Camp: out Pnode; Pid, Pidtipus: in Pnode);
   procedure rs_sentencies (Psents: out Pnode; Pcontlista, Psent: in Pnode);
   procedure rs_sentencies (Psents: out Pnode; psent: in pnode);
   procedure rs_sent_cond (Psent: out Pnode; Pcond: in Pnode);
   procedure rs_sent_assig (Psent: out Pnode; Pasig: in Pnode);
   procedure rs_sent_iter (Psent: out Pnode; Piter: in Pnode);
   procedure rs_sent_proc (Psent: out Pnode; pllam_proc: in pnode);
   procedure Rs_Cond (Pcond: out Pnode; Pexp, Psents: in Pnode);
   procedure Rs_Cond (Pcond: out Pnode; Pexp2, Psents2if, Psents2else: in Pnode);
   procedure rs_assignacio (Pasig: out Pnode; Pref, Pexp: in Pnode);
   procedure Rs_Ref (Pref: out Pnode; Pid, Pcalif: in Pnode);
   procedure rs_qualifs (Pcalfs: out Pnode; Pcontlista, Pcalif: in Pnode);
   procedure rs_qualifs (pcalfs: out Pnode);
   procedure rs_qualif_simple (Pcalf: out Pnode; Pid: in Pnode);
   procedure rs_qualif_complex (Pcalf: out Pnode; Pexp: in Pnode);
   procedure rs_iteracio (Piter: out Pnode; Pexp, Psents: in Pnode);
   procedure rs_crida_procediment (pllam_proc: out pnode; Pref: in Pnode);
   procedure rs_l_e (Pl_Exp: out Pnode; Pcontlista, Pexp: in Pnode);
   procedure rs_l_e (Pl_Exp: out Pnode; Pexp: in Pnode);
   procedure Rs_Suma (Psuma: out Pnode; Pexp1, Pexp2: in Pnode);
   procedure Rs_Resta (Presta: out Pnode; Pexp1, Pexp2: in Pnode);
   procedure Rs_Mult (Pmult: out Pnode; Pexp1, Pexp2: in Pnode);
   procedure Rs_div (pdiv: out pnode; Pexp1, pexp2: in Pnode);
   procedure Rs_mod (pmod: out pnode; Pexp1, pexp2: in Pnode);
   procedure Rs_and (pand: out pnode; Pexp1, pexp2: in Pnode);
   procedure Rs_Or (Por: out Pnode; Pexp1, Pexp2: in Pnode);
   procedure Rs_Major (Pmajor: out Pnode; Pexp1, Pexp2: in Pnode);
   procedure Rs_menor (pmenor: out pnode; Pexp1, pexp2: in Pnode);
   procedure Rs_Majorig (Pmajorig: out Pnode; Pexp1, Pexp2: in Pnode);
   procedure Rs_Menorig (Pmenorig: out Pnode; Pexp1, Pexp2: in Pnode);
   procedure Rs_Dif (Pdif: out Pnode; Pexp1, Pexp2: in Pnode);
   procedure Rs_Igual (Pigual: out Pnode; Pexp1, Pexp2: in Pnode);
   procedure Rs_Neg (Pneg: out Pnode; Pexp: in Pnode);
   procedure Rs_Parent (Pparent: out Pnode; Pexp: in Pnode);
   procedure Rs_Not (Pnot: out Pnode; Pexp: in Pnode);
   procedure Rs_Eref (Peref: out Pnode; Pexp: in Pnode);
   procedure Rs_Elit (Pelit: out Pnode; Pexp: in Pnode);

end semantica.C_Arbre;


